// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

type Todo struct {
	ID          int32
	Title       string
	Description string
	DueDate     string
	CreatedAt   string
	UpdatedAt   string
}
